version: '3.5'

services:
  redis-server:
    image: redis
  
  app:
    build: ./
    working_dir: /app
    volumes: 
      - ./:/app
    ports: 
        - 3000:3000
    
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL= redis://cache

    links:
      - redis-server
  
